//
//  PurchaseProduct.swift
//  InAppPurchaseSample
//
//  Created by uematsushun on 2020/09/26.
//

import Foundation
import StoreKit

protocol PurchasedResultNotification: AnyObject {
	/// Notify that the transaction is complete.
	/// - Parameter transaction: Finished transaction.
	func completed(transaction: SKPaymentTransaction)
	
	/// Notify that the transaction has failed.///
	/// - Parameter transaction: Failed transaction.
	func failed(transaction: SKPaymentTransaction)
}

final class PurchaseProduct: NSObject {
	
	private override init() { }
	static let shared = PurchaseProduct()
	
	weak var delegate: PurchasedResultNotification?
	
	func callAsFunction(product: SKProduct) {
		let payment = SKPayment(product: product)
		// Transaction is generated by enqueue to a payment queue
		SKPaymentQueue.default().add(payment)
	}
}

extension PurchaseProduct: SKPaymentTransactionObserver {
	func paymentQueue(_ queue: SKPaymentQueue, updatedTransactions transactions: [SKPaymentTransaction]) {
		transactions.forEach { transaction in
			switch transaction.transactionState {
				case .purchased, .restored:
					delegate?.completed(transaction: transaction)
					SKPaymentQueue.default().finishTransaction(transaction)
				case .failed:
					delegate?.failed(transaction: transaction)
					SKPaymentQueue.default().finishTransaction(transaction)
				case .purchasing, .deferred:
					break
				@unknown default:
					break
			}
		}
	}
}

class ViewModel: PurchasedResultNotification {
	func completed(transaction: SKPaymentTransaction) {
		SKPaymentQueue.default().finishTransaction(transaction)
	}
	
	func failed(transaction: SKPaymentTransaction) {
		SKPaymentQueue.default().finishTransaction(transaction)
	}
}
